# Generated by Django 4.2.6 on 2023-10-26 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partidos',
            name='pendiente',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='partidos',
            name='resultado',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
