# Generated by Django 4.2.6 on 2023-10-26 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Equipos', '0002_partidos_pendiente_partidos_resultado'),
    ]

    operations = [
        migrations.CreateModel(
            name='TablaPosiciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos', models.IntegerField()),
                ('partidos_jugados', models.IntegerField()),
                ('partidos_ganados', models.IntegerField()),
                ('partidos_empatados', models.IntegerField()),
                ('partidos_perdidos', models.IntegerField()),
                ('goles_a_favor', models.IntegerField()),
                ('goles_en_contra', models.IntegerField()),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Equipos.equipos')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Equipos.torneos')),
            ],
        ),
    ]
